name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: autonomx/setup-cmake@v1
      with:
        cmake-version: '3.18.4'      

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: message_handler
        path: build/message_handler
